### ISSUE TITLE
Add some more genres

### ISSUE THREAD

**Issue by swapn652** [kara-harshit/Book-list#1]
The choice of genres is limited. Add some more genres like Horror, Young Adult, etc. Also, create an option entitled as <b>Other</b>, which when chosen, shows another input option on the screen, in which you can type some not so common genres like Cyberpunk, Bangsian etc.

![image](https://user-images.githubusercontent.com/70851202/195123452-5c09b6b3-860a-4a78-b756-6f72cd4a4641.png)

Also, you can allow multiple genres to be chosen as for most of the times a book can belong to multiple genres. For example, a science fiction book can also be adventurous.

**Comment by kara-harshit** [comment]
adding "other" as option is really nice. i will surely add that. for now i have added some more genres.
